Repository auth0/symfony, pull requests merged in 2021-03, with the labels that each got.

#108 Introduce PHP 8.0 support and update to latest Auth0 PHP SDK version
  .circleci/config.yml
  .gitignore
  .phpcs-compat.xml.dist
  .phpcs.xml.dist
  LICENSE
  README.md
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/Functional/BundleInitializationTest.php
  Tests/Functional/config/cache.yml
  Tests/Security/Guard/JwtGuardAuthenticatorTest.php
  Tests/Security/Helpers/Auth0Psr16AdapterTest.php
  Tests/Security/Helpers/JwtValidationsTest.php
  Tests/Security/JWTAuthenticatorTest.php
  Tests/Security/User/JwtUserProviderTest.php
  codecov.yml
  composer.json
  composer.lock
  phpstan.neon.dist
  phpunit.xml.dist
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/JWTAuthExtension.php
  src/JWTAuthBundle.php
  src/Resources/config/services.yml
  src/Security/Auth0Service.php
  src/Security/Core/JWTInfoNotFoundException.php
  src/Security/Core/JWTUserProviderInterface.php
  src/Security/Guard/JwtGuardAuthenticator.php
  src/Security/Helpers/Auth0Psr16Adapter.php
  src/Security/Helpers/JwtValidations.php
  src/Security/JWTAuthenticator.php
  src/Security/User/JwtUserProvider.php
Labels: CH: Changed, review:medium

#111 [SDK-2377] Add optional validator for `org_id` on tokens, for Organizations support
  README.md
  Tests/Security/Helpers/JwtValidationsTest.php
  src/DependencyInjection/JWTAuthExtension.php
  src/Security/Helpers/JwtValidations.php
Labels: review:tiny

#112 Fix JwtGuardAuthenticator::supports behavior to avoid conflicting with other bundles
  src/Security/Guard/JwtGuardAuthenticator.php
Labels: bug, review:tiny

#113 Release 4.0.0
  CHANGELOG.md
  UPGRADING.md
  src/JWTAuthBundle.php
Labels: review:tiny
